# Generated by Django 4.0.2 on 2022-02-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='qualificaitons',
            new_name='qualifications',
        ),
    ]
