# Generated by Django 4.0.2 on 2022-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_qualificaitons_staff_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='images/staff/'),
        ),
    ]
