# Generated by Django 4.0.2 on 2022-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_subservice_icon'),
        ('staff', '0004_alter_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ManyToManyField(null=True, to='services.Services'),
        ),
    ]
