# Generated by Django 4.0.2 on 2022-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_subservice_icon'),
        ('staff', '0005_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ManyToManyField(to='services.Services'),
        ),
    ]
