# Generated by Django 4.0.2 on 2022-03-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='icon',
        ),
    ]
