# Generated by Django 4.0.2 on 2022-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=100)),
                ('Notes', models.TextField()),
                ('service', models.CharField(max_length=20)),
            ],
        ),
    ]
