# Generated by Django 4.0.2 on 2022-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_time_appointment_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
