# Generated by Django 4.0.2 on 2022-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(default='Morning', max_length=10),
        ),
    ]
