# Generated by Django 4.0.2 on 2022-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
