# Generated by Django 4.0.2 on 2022-03-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_email_alter_appointment_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_end',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_start',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
